/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'rss-feeds': RssFeed;
    'feed-automations': FeedAutomation;
    notifications: Notification;
    'automation-history': AutomationHistory;
    digests: Digest;
    'digest-runs': DigestRun;
    'result-feeds': ResultFeed;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'rss-feeds': RssFeedsSelect<false> | RssFeedsSelect<true>;
    'feed-automations': FeedAutomationsSelect<false> | FeedAutomationsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'automation-history': AutomationHistorySelect<false> | AutomationHistorySelect<true>;
    digests: DigestsSelect<false> | DigestsSelect<true>;
    'digest-runs': DigestRunsSelect<false> | DigestRunsSelect<true>;
    'result-feeds': ResultFeedsSelect<false> | ResultFeedsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    jobs: Job;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'process-feeds': TaskProcessFeeds;
      'deliver-notifications': TaskDeliverNotifications;
      'send-digests': TaskSendDigests;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rss-feeds".
 */
export interface RssFeed {
  id: string;
  name: string;
  type: 'rss' | 'reddit' | 'wordpress';
  url: string;
  enabled: boolean;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-automations".
 */
export interface FeedAutomation {
  id: string;
  name: string;
  enabled: boolean;
  type: 'rss' | 'reddit' | 'wordpress';
  /**
   * Optional: limit this automation to specific feeds.
   */
  feeds?: (string | RssFeed)[] | null;
  standardRules?: {
    /**
     * Model name to use (e.g., gpt-5-nano, openai/gpt-oss-120b, qwen/qwen3-next-80b).
     */
    model?: string | null;
    /**
     * Use "Yes" and "No" in the prompt to guide the AI in deciding whether to send a notification based on the RSS feed item content.
     */
    modelPrompt?: string | null;
    notifyEveryPost?: boolean | null;
  };
  redditRules?: {
    followPostRss?: boolean | null;
    processComments?: boolean | null;
  };
  wordpressRules?: {
    followPostRss?: boolean | null;
    processComments?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  title: string;
  message?: string | null;
  sourceURL?: string | null;
  automation: string | FeedAutomation;
  feed?: (string | null) | RssFeed;
  matchedAt: string;
  overallStatus: 'pending' | 'sent' | 'failed' | 'skipped';
  delivery: {
    email: {
      status: 'pending' | 'sent' | 'failed' | 'skipped';
      sentAt?: string | null;
      error?: string | null;
    };
    ntfy: {
      status: 'pending' | 'sent' | 'failed' | 'skipped';
      sentAt?: string | null;
      error?: string | null;
    };
  };
  /**
   * Raw alert payload for debugging and auditing.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-history".
 */
export interface AutomationHistory {
  id: string;
  /**
   * Stable dedupe key for a feed item within a specific automation.
   */
  itemKey: string;
  status: 'notified' | 'ignored';
  /**
   * Why this item ended up with its recorded status.
   */
  reason?: string | null;
  automation: string | FeedAutomation;
  feed: string | RssFeed;
  sourceURL?: string | null;
  title?: string | null;
  matchedAt?: string | null;
  processedAt: string;
  /**
   * Total number of evaluation attempts for this item.
   */
  attemptCount: number;
  /**
   * How many retries were attempted after the initial ignored result.
   */
  retryCount: number;
  /**
   * When this ignored item becomes eligible for another evaluation.
   */
  nextRetryAt?: string | null;
  retryExhausted: boolean;
  notification?: (string | null) | Notification;
  /**
   * Chronological log of each evaluation attempt for this item.
   */
  checks?:
    | {
        checkedAt: string;
        status: 'notified' | 'ignored';
        reason?: string | null;
        attemptNumber: number;
        retryNumber: number;
        nextRetryAt?: string | null;
        notification?: (string | null) | Notification;
        id?: string | null;
      }[]
    | null;
  /**
   * Raw processing payload for debugging and auditing.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digests".
 */
export interface Digest {
  id: string;
  name: string;
  enabled: boolean;
  schedule: {
    /**
     * 24-hour time in HH:mm format, evaluated in the selected timezone.
     */
    time: string;
    timezone:
      | 'America/New_York'
      | 'America/Chicago'
      | 'America/Denver'
      | 'America/Los_Angeles'
      | 'UTC'
      | 'Europe/London'
      | 'Europe/Berlin'
      | 'Asia/Tokyo'
      | 'Australia/Sydney';
  };
  /**
   * Optional. When empty, the digest uses Settings > Notifications > Email recipients.
   */
  recipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Limit this digest to notifications from selected automations.
   */
  automations?: (string | FeedAutomation)[] | null;
  /**
   * Optional. Limit this digest to notifications from selected feeds.
   */
  feeds?: (string | RssFeed)[] | null;
  /**
   * How far back to look for matching notifications when a digest has not run before.
   */
  lookbackHours: number;
  /**
   * Maximum number of notifications to include in one digest email.
   */
  maxNotifications: number;
  useAI: boolean;
  /**
   * Additional system prompt instructions for summarizing this digest.
   */
  instructions?: string | null;
  /**
   * Optional instructions for how AI should rank and group notifications.
   */
  priorityInstructions?: string | null;
  lastRunAt?: string | null;
  lastSuccessAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digest-runs".
 */
export interface DigestRun {
  id: string;
  digest: string | Digest;
  /**
   * Stable key used to prevent duplicate sends for the same digest window.
   */
  runKey: string;
  status: 'pending' | 'sent' | 'failed' | 'skipped';
  windowStart: string;
  windowEnd: string;
  sentAt?: string | null;
  notifications?: (string | Notification)[] | null;
  subject?: string | null;
  text?: string | null;
  html?: string | null;
  /**
   * Structured model response and metadata used to build the digest.
   */
  aiOutput?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public or private Atom/RSS feeds of generated notification and digest results. Public feeds are unprotected; private feeds require the tokenized URL.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "result-feeds".
 */
export interface ResultFeed {
  id: string;
  name: string;
  enabled: boolean;
  resultType: 'notifications' | 'digests';
  /**
   * Public feeds are visible to anyone with the URL. Private feeds require the token.
   */
  visibility: 'private' | 'public';
  /**
   * Secret token required for private feed URLs. Rotate by replacing this value.
   */
  token: string;
  format: 'atom' | 'rss';
  limit: number;
  /**
   * Optional. Limit notification feeds to selected automations.
   */
  automations?: (string | FeedAutomation)[] | null;
  /**
   * Optional. Limit notification feeds to selected source feeds.
   */
  feeds?: (string | RssFeed)[] | null;
  /**
   * Optional. Limit digest feeds to selected digest definitions.
   */
  digests?: (string | Digest)[] | null;
  /**
   * Optional. Notification feeds default to sent results. Digest feeds default to sent digest runs.
   */
  statuses?: ('pending' | 'sent' | 'failed' | 'skipped')[] | null;
  includeContent: boolean;
  feedURL?: string | null;
  lastAccessedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'process-feeds' | 'deliver-notifications' | 'send-digests';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'process-feeds' | 'deliver-notifications' | 'send-digests') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'rss-feeds';
        value: string | RssFeed;
      } | null)
    | ({
        relationTo: 'feed-automations';
        value: string | FeedAutomation;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'automation-history';
        value: string | AutomationHistory;
      } | null)
    | ({
        relationTo: 'digests';
        value: string | Digest;
      } | null)
    | ({
        relationTo: 'digest-runs';
        value: string | DigestRun;
      } | null)
    | ({
        relationTo: 'result-feeds';
        value: string | ResultFeed;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rss-feeds_select".
 */
export interface RssFeedsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  url?: T;
  enabled?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-automations_select".
 */
export interface FeedAutomationsSelect<T extends boolean = true> {
  name?: T;
  enabled?: T;
  type?: T;
  feeds?: T;
  standardRules?:
    | T
    | {
        model?: T;
        modelPrompt?: T;
        notifyEveryPost?: T;
      };
  redditRules?:
    | T
    | {
        followPostRss?: T;
        processComments?: T;
      };
  wordpressRules?:
    | T
    | {
        followPostRss?: T;
        processComments?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  sourceURL?: T;
  automation?: T;
  feed?: T;
  matchedAt?: T;
  overallStatus?: T;
  delivery?:
    | T
    | {
        email?:
          | T
          | {
              status?: T;
              sentAt?: T;
              error?: T;
            };
        ntfy?:
          | T
          | {
              status?: T;
              sentAt?: T;
              error?: T;
            };
      };
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "automation-history_select".
 */
export interface AutomationHistorySelect<T extends boolean = true> {
  itemKey?: T;
  status?: T;
  reason?: T;
  automation?: T;
  feed?: T;
  sourceURL?: T;
  title?: T;
  matchedAt?: T;
  processedAt?: T;
  attemptCount?: T;
  retryCount?: T;
  nextRetryAt?: T;
  retryExhausted?: T;
  notification?: T;
  checks?:
    | T
    | {
        checkedAt?: T;
        status?: T;
        reason?: T;
        attemptNumber?: T;
        retryNumber?: T;
        nextRetryAt?: T;
        notification?: T;
        id?: T;
      };
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digests_select".
 */
export interface DigestsSelect<T extends boolean = true> {
  name?: T;
  enabled?: T;
  schedule?:
    | T
    | {
        time?: T;
        timezone?: T;
      };
  recipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  automations?: T;
  feeds?: T;
  lookbackHours?: T;
  maxNotifications?: T;
  useAI?: T;
  instructions?: T;
  priorityInstructions?: T;
  lastRunAt?: T;
  lastSuccessAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digest-runs_select".
 */
export interface DigestRunsSelect<T extends boolean = true> {
  digest?: T;
  runKey?: T;
  status?: T;
  windowStart?: T;
  windowEnd?: T;
  sentAt?: T;
  notifications?: T;
  subject?: T;
  text?: T;
  html?: T;
  aiOutput?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "result-feeds_select".
 */
export interface ResultFeedsSelect<T extends boolean = true> {
  name?: T;
  enabled?: T;
  resultType?: T;
  visibility?: T;
  token?: T;
  format?: T;
  limit?: T;
  automations?: T;
  feeds?: T;
  digests?: T;
  statuses?: T;
  includeContent?: T;
  feedURL?: T;
  lastAccessedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  modelSettings?: {
    /**
     * Used when an automation does not set its own model. Falls back to the MODEL_NAME env var, then gpt-5-nano.
     */
    defaultModel?: string | null;
    /**
     * Additional system instructions prepended before the evaluation prompt.
     */
    systemPrompt?: string | null;
  };
  firecrawl?: {
    /**
     * Optional Firecrawl base URL used for RSS retrieval, for example https://api.firecrawl.dev or http://localhost:3001.
     */
    host?: string | null;
    /**
     * Optional Firecrawl auth token. Leave blank for self-hosted instances that do not require one.
     */
    token?: string | null;
  };
  notifications: {
    email: {
      enabled: boolean;
      fromName?: string | null;
      fromEmail?: string | null;
      replyTo?: string | null;
      /**
       * Email addresses that receive alert notifications.
       */
      recipients?:
        | {
            email: string;
            id?: string | null;
          }[]
        | null;
    };
    ntfy: {
      enabled: boolean;
      /**
       * Base URL for your ntfy server (e.g., https://ntfy.sh).
       */
      serverURL?: string | null;
      /**
       * Auth token for ntfy (leave blank if not needed).
       */
      authToken?: string | null;
      /**
       * One or more ntfy topics to publish alerts to.
       */
      channels?:
        | {
            topic: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  modelSettings?:
    | T
    | {
        defaultModel?: T;
        systemPrompt?: T;
      };
  firecrawl?:
    | T
    | {
        host?: T;
        token?: T;
      };
  notifications?:
    | T
    | {
        email?:
          | T
          | {
              enabled?: T;
              fromName?: T;
              fromEmail?: T;
              replyTo?: T;
              recipients?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
            };
        ntfy?:
          | T
          | {
              enabled?: T;
              serverURL?: T;
              authToken?: T;
              channels?:
                | T
                | {
                    topic?: T;
                    id?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskProcess-feeds".
 */
export interface TaskProcessFeeds {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDeliver-notifications".
 */
export interface TaskDeliverNotifications {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-digests".
 */
export interface TaskSendDigests {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}